global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "monitor-job"
    static_configs:
      - targets: ["monitor:3000"]

  - job_name: "otel-collector"
    static_configs: [{ targets: ["otel-collector:9464"] }]
