name: Infra-Latte

on:
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  format:
    name: formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use ACM Formatting
        uses: acm-ucr/formatting@v2

  # lint:
  #   name: linting
  #   runs-on: ubuntu-latest

  # steps:
  #   - uses: actions/checkout@v4
  #   - name: Use ACM Linting
  #     uses: acm-ucr/linting@v2

  test:
    name: tests
    runs-on: ubuntu-latest
    # needs: [lint]
    env:
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.3

      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Run Jest (CI mode + coverage)
        run: bunx jest --ci --coverage

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
          if-no-files-found: ignore

  build:
    name: build
    runs-on: ubuntu-latest
    needs: [format, test]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.3

      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Build with Bun
        run: bun run build
